<script setup lang="ts"></script>

<template>
  <div class="">
    anime
    <div>1n</div>
    <div>2n</div>
    <div>3n</div>
    <div>4n</div>
    <div>5n</div>
    <div>6n</div>
    <div>7n</div>
    <div>8n</div>
    <div>9n</div>
    <div>10n</div>
    <div>11n</div>
    <div>12n</div>
    <div>13n</div>
    <div>14n</div>
    <div>15n</div>
    <div>16n</div>
    <div>17n</div>
    <div>18n</div>
    <div>19n</div>
    <div>20n</div>
    <div>21n</div>
    <div>22n</div>
    <div>23n</div>
    <div>24n</div>
    <div>25n</div>
    <div>26n</div>
    <div>27n</div>
    <div>28n</div>
    <div>29n</div>
    <div>30n</div>
    <div>31n</div>
    <div>32n</div>
    <div>33n</div>
    <div>34n</div>
    <div>35n</div>
    <div>36n</div>
    <div>37n</div>
    <div>38n</div>
    <div>39n</div>
    <div>40n</div>
    <div>41n</div>
    <div>42n</div>
    <div>43n</div>
    <div>44n</div>
    <div>45n</div>
    <div>46n</div>
    <div>47n</div>
    <div>48n</div>
    <div>49n</div>
    <div>50n</div>
    <div>51n</div>
    <div>52n</div>
    <div>53n</div>
    <div>54n</div>
    <div>55n</div>
    <div>56n</div>
    <div>57n</div>
    <div>58n</div>
    <div>59n</div>
    <div>60n</div>
    <div>61n</div>
    <div>62n</div>
    <div>63n</div>
    <div>64n</div>
    <div>65n</div>
    <div>66n</div>
    <div>67n</div>
    <div>68n</div>
    <div>69n</div>
    <div>70n</div>
    <div>71n</div>
    <div>72n</div>
    <div>73n</div>
    <div>74n</div>
    <div>75n</div>
    <div>76n</div>
    <div>77n</div>
    <div>78n</div>
    <div>79n</div>
    <div>80n</div>
    <div>81n</div>
    <div>82n</div>
    <div>83n</div>
    <div>84n</div>
    <div>85n</div>
    <div>86n</div>
    <div>87n</div>
    <div>88n</div>
    <div>89n</div>
    <div>90n</div>
    <div>91n</div>
    <div>92n</div>
    <div>93n</div>
    <div>94n</div>
    <div>95n</div>
    <div>96n</div>
    <div>97n</div>
    <div>98n</div>
    <div>99n</div>
    <div>100n</div>
  </div>
</template>

<style scoped></style>
