export const themeList = [
  {
    name: '立春',
    color: '#94B79E',
    bgColor: '#E7F3CF',
    picture: '/imgs/HeiSolarTerms/202101.jpg',
    poetryPicture: '/imgs/HeiSolarTerms/202401_poetry.png',
  },
  {
    name: '雨水',
    color: '#F8B1A3',
    bgColor: '#BDD2D7',
    picture: '/imgs/HeiSolarTerms/202102.jpg',
    poetryPicture: '/imgs/HeiSolarTerms/202402_poetry.png',
  },
  {
    name: '惊蛰',
    color: '#F6C9A7',
    bgColor: '#D9D9D9',
    picture: '/imgs/HeiSolarTerms/202103.jpg',
    poetryPicture: '/imgs/HeiSolarTerms/202403_poetry.png',
  },
  {
    name: '春分',
    color: '#FBE4A4',
    bgColor: '#F2E8D9',
    picture: '/imgs/HeiSolarTerms/202104.jpg',
    poetryPicture: '/imgs/HeiSolarTerms/202404_poetry.png',
  },
  {
    name: '清明',
    color: '#A4C2F4',
    bgColor: '#E8E8E8',
    picture: '/imgs/HeiSolarTerms/202105.jpg',
    poetryPicture: '/imgs/HeiSolarTerms/202405_poetry.png',
  },
  {
    name: '谷雨',
    color: '#B3E1A4',
    bgColor: '#E8E8E8',
    picture: '/imgs/HeiSolarTerms/202106.jpg',
    poetryPicture: '/imgs/HeiSolarTerms/202406_poetry.png',
  },
  {
    name: '立夏',
    color: '#F4A4A4',
    bgColor: '#E8E8E8',
    picture: '/imgs/HeiSolarTerms/202107.jpg',
    poetryPicture: '/imgs/HeiSolarTerms/202407_poetry.png',
  },
  {
    name: '小满',
    color: '#A4E1A4',
    bgColor: '#E8E8E8',
    picture: '/imgs/HeiSolarTerms/202108.jpg',
    poetryPicture: '/imgs/HeiSolarTerms/202408_poetry.png',
  },
  {
    name: '芒种',
    color: '#A4C2F4',
    bgColor: '#E8E8E8',
    picture: '/imgs/HeiSolarTerms/202109.jpg',
    poetryPicture: '/imgs/HeiSolarTerms/202409_poetry.png',
  },
  {
    name: '夏至',
    color: '#F4A4A4',
    bgColor: '#E8E8E8',
    picture: '/imgs/HeiSolarTerms/202110.jpg',
    poetryPicture: '/imgs/HeiSolarTerms/202410_poetry.png',
  },
  {
    name: '小暑',
    color: '#A4E1A4',
    bgColor: '#E8E8E8',
    picture: '/imgs/HeiSolarTerms/202111.jpg',
    poetryPicture: '/imgs/HeiSolarTerms/202411_poetry.png',
  },
  {
    name: '大暑',
    color: '#A4C2F4',
    bgColor: '#E8E8E8',
    picture: '/imgs/HeiSolarTerms/202112.jpg',
    poetryPicture: '/imgs/HeiSolarTerms/202412_poetry.png',
  },
  {
    name: '立秋',
    color: '#F4A4A4',
    bgColor: '#E8E8E8',
    picture: '/imgs/HeiSolarTerms/202113.jpg',
    poetryPicture: '/imgs/HeiSolarTerms/202413_poetry.png',
  },
  {
    name: '处暑',
    color: '#A4E1A4',
    bgColor: '#E8E8E8',
    picture: '/imgs/HeiSolarTerms/202114.jpg',
    poetryPicture: '/imgs/HeiSolarTerms/202414_poetry.png',
  },
  {
    name: '白露',
    color: '#A4C2F4',
    bgColor: '#E8E8E8',
    picture: '/imgs/HeiSolarTerms/202115.jpg',
    poetryPicture: '/imgs/HeiSolarTerms/202415_poetry.png',
  },
  {
    name: '秋分',
    color: '#F4A4A4',
    bgColor: '#E8E8E8',
    picture: '/imgs/HeiSolarTerms/202116.jpg',
    poetryPicture: '/imgs/HeiSolarTerms/202416_poetry.png',
  },
  {
    name: '寒露',
    color: '#A4E1A4',
    bgColor: '#E8E8E8',
    picture: '/imgs/HeiSolarTerms/202117.jpg',
    poetryPicture: '/imgs/HeiSolarTerms/202417_poetry.png',
  },
  {
    name: '霜降',
    color: '#A4C2F4',
    bgColor: '#E8E8E8',
    picture: '/imgs/HeiSolarTerms/202118.jpg',
    poetryPicture: '/imgs/HeiSolarTerms/202418_poetry.png',
  },
  {
    name: '立冬',
    color: '#F4A4A4',
    bgColor: '#E8E8E8',
    picture: '/imgs/HeiSolarTerms/202119.jpg',
    poetryPicture: '/imgs/HeiSolarTerms/202419_poetry.png',
  },
  {
    name: '小雪',
    color: '#A4E1A4',
    bgColor: '#E8E8E8',
    picture: '/imgs/HeiSolarTerms/202120.jpg',
    poetryPicture: '/imgs/HeiSolarTerms/202420_poetry.png',
  },
  {
    name: '大雪',
    color: '#A4C2F4',
    bgColor: '#E8E8E8',
    picture: '/imgs/HeiSolarTerms/202121.jpg',
    poetryPicture: '/imgs/HeiSolarTerms/202421_poetry.png',
  },
  {
    name: '冬至',
    color: '#F4A4A4',
    bgColor: '#E8E8E8',
    picture: '/imgs/HeiSolarTerms/202122.jpg',
    poetryPicture: '/imgs/HeiSolarTerms/202422_poetry.png',
  },
  {
    name: '小寒',
    color: '#A4E1A4',
    bgColor: '#E8E8E8',
    picture: '/imgs/HeiSolarTerms/202123.jpg',
    poetryPicture: '/imgs/HeiSolarTerms/202423_poetry.png',
  },
  {
    name: '大寒',
    color: '#A4C2F4',
    bgColor: '#E8E8E8',
    picture: '/imgs/HeiSolarTerms/202124.jpg',
    poetryPicture: '/imgs/HeiSolarTerms/202424_poetry.png',
  },
]
