export const themeList = [
  {
    name: '立春',
    description: '春芽初绽',
    colors: {
      primary: '#5A7A5A',
      accent: '#C8D9C8',
      background: '#F8FAF8',
      ring: '#A8C5A8',
    },
    poetry: '东风解冻，蛰虫始振，鱼陟负冰',
    poetryPicture: '/imgs/HeiSolarTerms/202401_poetry.png',
  },
  {
    name: '雨水',
    description: '春雨润泽',
    colors: {
      primary: '#5A8A8A',
      accent: '#C5DEDE',
      background: '#F7FAFA',
      ring: '#A3D0D0',
    },
    poetry: '獭祭鱼，鸿雁来，草木萌动',
    poetryPicture: '/imgs/HeiSolarTerms/202402_poetry.png',
  },
  {
    name: '惊蛰',
    description: '万物复苏',
    colors: {
      primary: '#6B8A5A',
      accent: '#D1E0C8',
      background: '#F9FBF8',
      ring: '#B0D0A0',
    },
    poetry: '桃始华，仓庚鸣，鹰化为鸠',
    poetryPicture: '/imgs/HeiSolarTerms/202403_poetry.png',
  },
  {
    name: '春分',
    description: '昼夜平分',
    colors: {
      primary: '#7A6B8A',
      accent: '#E0D8E8',
      background: '#FAF9FB',
      ring: '#C8B8D8',
    },
    poetry: '玄鸟至，雷乃发声，始电',
    poetryPicture: '/imgs/HeiSolarTerms/202404_poetry.png',
  },
  {
    name: '清明',
    description: '清澈明朗',
    colors: {
      primary: '#6B8A9A',
      accent: '#D1E0E8',
      background: '#F9FBFB',
      ring: '#B0D0E0',
    },
    poetry: '桐始华，田鼠化为鴽，虹始见',
    poetryPicture: '/imgs/HeiSolarTerms/202405_poetry.png',
  },
  {
    name: '谷雨',
    description: '滋润万物',
    colors: {
      primary: '#6B8A6B',
      accent: '#D1E0D1',
      background: '#F9FBF9',
      ring: '#B0D0B0',
    },
    poetry: '萍始生，鸣鸠拂其羽，戴胜降于桑',
    poetryPicture: '/imgs/HeiSolarTerms/202406_poetry.png',
  },
  {
    name: '立夏',
    description: '夏日初临',
    colors: {
      primary: '#8A6B5A',
      accent: '#E8D8C8',
      background: '#FBF9F8',
      ring: '#D8C0A8',
    },
    poetry: '蝼蝈鸣，蚯蚓出，王瓜生',
    poetryPicture: '/imgs/HeiSolarTerms/202407_poetry.png',
  },
  {
    name: '小满',
    description: '麦穗初成',
    colors: {
      primary: '#9A7A5A',
      accent: '#F0E0D0',
      background: '#FBF9F8',
      ring: '#E0C8A8',
    },
    poetry: '苦菜秀，靡草死，麦秋至',
    poetryPicture: '/imgs/HeiSolarTerms/202408_poetry.png',
  },
  {
    name: '芒种',
    description: '农忙时节',
    colors: {
      primary: '#8A7A5A',
      accent: '#E8D8C8',
      background: '#FBF9F8',
      ring: '#D8C8A8',
    },
    poetry: '螳螂生，鵙始鸣，反舌无声',
    poetryPicture: '/imgs/HeiSolarTerms/202409_poetry.png',
  },
  {
    name: '夏至',
    description: '盛夏炽阳',
    colors: {
      primary: '#8A6B5A',
      accent: '#E0D1C8',
      background: '#FAF9F8',
      ring: '#D0B8A0',
    },
    poetry: '鹿角解，蜩始鸣，半夏生',
    poetryPicture: '/imgs/HeiSolarTerms/202410_poetry.png',
  },
  {
    name: '小暑',
    description: '暑气渐浓',
    colors: {
      primary: '#9A6A6A',
      accent: '#E8D0D0',
      background: '#FBF9F9',
      ring: '#E0B8B8',
    },
    poetry: '温风至，蟋蟀居宇，鹰始挚',
    poetryPicture: '/imgs/HeiSolarTerms/202411_poetry.png',
  },
  {
    name: '大暑',
    description: '酷热难当',
    colors: {
      primary: '#8A5A5A',
      accent: '#E0C8C8',
      background: '#FAF9F9',
      ring: '#D0B0A0',
    },
    poetry: '腐草为萤，土润溽暑，大雨时行',
    poetryPicture: '/imgs/HeiSolarTerms/202412_poetry.png',
  },
  {
    name: '立秋',
    description: '秋意初现',
    colors: {
      primary: '#9A8A7A',
      accent: '#E8D8D0',
      background: '#FBF9F8',
      ring: '#E0C8B0',
    },
    poetry: '凉风至，白露生，寒蝉鸣',
    poetryPicture: '/imgs/HeiSolarTerms/202413_poetry.png',
  },
  {
    name: '处暑',
    description: '暑热渐消',
    colors: {
      primary: '#8A7A6A',
      accent: '#E0D8C8',
      background: '#FAF9F8',
      ring: '#D0C0A8',
    },
    poetry: '鹰乃祭鸟，天地始肃，禾乃登',
    poetryPicture: '/imgs/HeiSolarTerms/202414_poetry.png',
  },
  {
    name: '白露',
    description: '露珠晶莹',
    colors: {
      primary: '#9AAA9A',
      accent: '#E8F0E8',
      background: '#FBFBFB',
      ring: '#E0E8D8',
    },
    poetry: '鸿雁来，玄鸟归，群鸟养羞',
    poetryPicture: '/imgs/HeiSolarTerms/202415_poetry.png',
  },
  {
    name: '秋分',
    description: '秋高气爽',
    colors: {
      primary: '#AA9A8A',
      accent: '#F0E8D8',
      background: '#FBFBF9',
      ring: '#E8D8C0',
    },
    poetry: '雷始收声，蛰虫坯户，水始涸',
    poetryPicture: '/imgs/HeiSolarTerms/202416_poetry.png',
  },
  {
    name: '寒露',
    description: '秋寒渐起',
    colors: {
      primary: '#8A9AAA',
      accent: '#E0E8F0',
      background: '#F9FAFB',
      ring: '#D0D8E0',
    },
    poetry: '鸿雁来宾，雀入大水为蛤，菊有黄华',
    poetryPicture: '/imgs/HeiSolarTerms/202417_poetry.png',
  },
  {
    name: '霜降',
    description: '霜华满地',
    colors: {
      primary: '#AAAAAA',
      accent: '#F0F0F0',
      background: '#FBFBFB',
      ring: '#E8E8E0',
    },
    poetry: '豺乃祭兽，草木黄落，蛰虫咸俯',
    poetryPicture: '/imgs/HeiSolarTerms/202418_poetry.png',
  },
  {
    name: '立冬',
    description: '冬季来临',
    colors: {
      primary: '#6B7A8A',
      accent: '#D1D8E0',
      background: '#F9FAFB',
      ring: '#B0C0C8',
    },
    poetry: '水始冰，地始冻，雉入大水为蜃',
    poetryPicture: '/imgs/HeiSolarTerms/202419_poetry.png',
  },
  {
    name: '小雪',
    description: '雪花初降',
    colors: {
      primary: '#7A8A9A',
      accent: '#D8E0E8',
      background: '#F9FAFB',
      ring: '#B8C8D0',
    },
    poetry: '虹藏不见，天气上升，闭塞成冬',
    poetryPicture: '/imgs/HeiSolarTerms/202420_poetry.png',
  },
  {
    name: '大雪',
    description: '雪满天地',
    colors: {
      primary: '#9AAA9A',
      accent: '#E8F0F0',
      background: '#FAFBFB',
      ring: '#E0E8E8',
    },
    poetry: '鹖鴠不鸣，虎始交，荔挺出',
    poetryPicture: '/imgs/HeiSolarTerms/202421_poetry.png',
  },
  {
    name: '冬至',
    description: '一阳来复',
    colors: {
      primary: '#6B7A8A',
      accent: '#D1D8E0',
      background: '#F9FAFB',
      ring: '#B0C0C8',
    },
    poetry: '蚯蚓结，麋角解，水泉动',
    poetryPicture: '/imgs/HeiSolarTerms/202422_poetry.png',
  },
  {
    name: '小寒',
    description: '寒意渐深',
    colors: {
      primary: '#5A6B7A',
      accent: '#C8D1D8',
      background: '#F8F9FA',
      ring: '#A8B8C0',
    },
    poetry: '雁北乡，鹊始巢，雉始鸲',
    poetryPicture: '/imgs/HeiSolarTerms/202423_poetry.png',
  },
  {
    name: '大寒',
    description: '严寒彻骨',
    colors: {
      primary: '#5A6A7A',
      accent: '#C8D0D8',
      background: '#F8F9FA',
      ring: '#A8B0B8',
    },
    poetry: '鸡乳，征鸟厉疾，水泽腹坚',
    poetryPicture: '/imgs/HeiSolarTerms/202424_poetry.png',
  },
]
