export const themeList = [
  {
    name: '立春',
    description: '春芽初绽',
    colors: {
      primary: '#7CB342',
      accent: '#E1BEE7',
      background: '#F1F8E9',
      ring: '#E8F5E8',
    },
    poetry: '东风解冻，蛰虫始振，鱼陟负冰',
    poetryPicture: '/imgs/HeiSolarTerms/202401_poetry.png',
  },
  {
    name: '雨水',
    description: '春雨润泽',
    colors: {
      primary: '#26A69A',
      accent: '#F8BBD9',
      background: '#E0F2F1',
      ring: '#B2DFDB',
    },
    poetry: '獭祭鱼，鸿雁来，草木萌动',
    poetryPicture: '/imgs/HeiSolarTerms/202402_poetry.png',
  },
  {
    name: '惊蛰',
    description: '万物复苏',
    colors: {
      primary: '#8BC34A',
      accent: '#FFB74D',
      background: '#F9FBE7',
      ring: '#DCEDC8',
    },
    poetry: '桃始华，仓庚鸣，鹰化为鸠',
    poetryPicture: '/imgs/HeiSolarTerms/202403_poetry.png',
  },
  {
    name: '春分',
    description: '昼夜平分',
    colors: {
      primary: '#EC407A',
      accent: '#81D4FA',
      background: '#FCE4EC',
      ring: '#E1F5FE',
    },
    poetry: '玄鸟至，雷乃发声，始电',
    poetryPicture: '/imgs/HeiSolarTerms/202404_poetry.png',
  },
  {
    name: '清明',
    description: '清澈明朗',
    colors: {
      primary: '#42A5F5',
      accent: '#AED581',
      background: '#E3F2FD',
      ring: '#C8E6C9',
    },
    poetry: '桐始华，田鼠化为鴽，虹始见',
    poetryPicture: '/imgs/HeiSolarTerms/202405_poetry.png',
  },
  {
    name: '谷雨',
    description: '滋润万物',
    colors: {
      primary: '#689F38',
      accent: '#FFCC02',
      background: '#F1F8E9',
      ring: '#DCEDC8',
    },
    poetry: '萍始生，鸣鸠拂其羽，戴胜降于桑',
    poetryPicture: '/imgs/HeiSolarTerms/202406_poetry.png',
  },
  {
    name: '立夏',
    description: '夏日初临',
    colors: {
      primary: '#FF5722',
      accent: '#26C6DA',
      background: '#FFF3E0',
      ring: '#B2EBF2',
    },
    poetry: '蝼蝈鸣，蚯蚓出，王瓜生',
    poetryPicture: '/imgs/HeiSolarTerms/202407_poetry.png',
  },
  {
    name: '小满',
    description: '麦穗初成',
    colors: {
      primary: '#FFB300',
      accent: '#66BB6A',
      background: '#FFFDE7',
      ring: '#C8E6C9',
    },
    poetry: '苦菜秀，靡草死，麦秋至',
    poetryPicture: '/imgs/HeiSolarTerms/202408_poetry.png',
  },
  {
    name: '芒种',
    description: '农忙时节',
    colors: {
      primary: '#4CAF50',
      accent: '#FFC107',
      background: '#E8F5E8',
      ring: '#FFF9C4',
    },
    poetry: '螳螂生，鵙始鸣，反舌无声',
    poetryPicture: '/imgs/HeiSolarTerms/202409_poetry.png',
  },
  {
    name: '夏至',
    description: '盛夏炽阳',
    colors: {
      primary: '#1976D2',
      accent: '#FF7043',
      background: '#E3F2FD',
      ring: '#FFCCBC',
    },
    poetry: '鹿角解，蜩始鸣，半夏生',
    poetryPicture: '/imgs/HeiSolarTerms/202410_poetry.png',
  },
  {
    name: '小暑',
    description: '暑气渐浓',
    colors: {
      primary: '#D32F2F',
      accent: '#9C27B0',
      background: '#FCE4EC',
      ring: '#E1BEE7',
    },
    poetry: '温风至，蟋蟀居宇，鹰始挚',
    poetryPicture: '/imgs/HeiSolarTerms/202411_poetry.png',
  },
  {
    name: '大暑',
    description: '酷热难当',
    colors: {
      primary: '#3F51B5',
      accent: '#FF9800',
      background: '#E8EAF6',
      ring: '#FFE0B2',
    },
    poetry: '腐草为萤，土润溽暑，大雨时行',
    poetryPicture: '/imgs/HeiSolarTerms/202412_poetry.png',
  },
  {
    name: '立秋',
    description: '秋意初现',
    colors: {
      primary: '#FF8F00',
      accent: '#8D6E63',
      background: '#FFF8E1',
      ring: '#FFCCBC',
    },
    poetry: '凉风至，白露生，寒蝉鸣',
    poetryPicture: '/imgs/HeiSolarTerms/202413_poetry.png',
  },
  {
    name: '处暑',
    description: '暑热渐消',
    colors: {
      primary: '#FF9800',
      accent: '#795548',
      background: '#FFF3E0',
      ring: '#D7CCC8',
    },
    poetry: '鹰乃祭鸟，天地始肃，禾乃登',
    poetryPicture: '/imgs/HeiSolarTerms/202414_poetry.png',
  },
  {
    name: '白露',
    description: '露珠晶莹',
    colors: {
      primary: '#90A4AE',
      accent: '#81C784',
      background: '#FAFAFA',
      ring: '#E8F5E8',
    },
    poetry: '鸿雁来，玄鸟归，群鸟养羞',
    poetryPicture: '/imgs/HeiSolarTerms/202415_poetry.png',
  },
  {
    name: '秋分',
    description: '秋高气爽',
    colors: {
      primary: '#F57C00',
      accent: '#A1887F',
      background: '#FFF8E1',
      ring: '#FFCC02',
    },
    poetry: '雷始收声，蛰虫坯户，水始涸',
    poetryPicture: '/imgs/HeiSolarTerms/202416_poetry.png',
  },
  {
    name: '寒露',
    description: '秋寒渐起',
    colors: {
      primary: '#5472D3',
      accent: '#FFB74D',
      background: '#E1F5FE',
      ring: '#FFF3E0',
    },
    poetry: '鸿雁来宾，雀入大水为蛤，菊有黄华',
    poetryPicture: '/imgs/HeiSolarTerms/202417_poetry.png',
  },
  {
    name: '霜降',
    description: '霜华满地',
    colors: {
      primary: '#B0BEC5',
      accent: '#FFAB91',
      background: '#F5F5F5',
      ring: '#FFCCBC',
    },
    poetry: '豺乃祭兽，草木黄落，蛰虫咸俯',
    poetryPicture: '/imgs/HeiSolarTerms/202418_poetry.png',
  },
  {
    name: '立冬',
    description: '冬季来临',
    colors: {
      primary: '#607D8B',
      accent: '#A1887F',
      background: '#ECEFF1',
      ring: '#D7CCC8',
    },
    poetry: '水始冰，地始冻，雉入大水为蜃',
    poetryPicture: '/imgs/HeiSolarTerms/202419_poetry.png',
  },
  {
    name: '小雪',
    description: '雪花初降',
    colors: {
      primary: '#78909C',
      accent: '#FFC107',
      background: '#F5F5F5',
      ring: '#FFF8E1',
    },
    poetry: '虹藏不见，天气上升，闭塞成冬',
    poetryPicture: '/imgs/HeiSolarTerms/202420_poetry.png',
  },
  {
    name: '大雪',
    description: '雪满天地',
    colors: {
      primary: '#CFD8DC',
      accent: '#64B5F6',
      background: '#FAFAFA',
      ring: '#E1F5FE',
    },
    poetry: '鹖鴠不鸣，虎始交，荔挺出',
    poetryPicture: '/imgs/HeiSolarTerms/202421_poetry.png',
  },
  {
    name: '冬至',
    description: '一阳来复',
    colors: {
      primary: '#455A64',
      accent: '#FFB74D',
      background: '#F5F5F5',
      ring: '#FFF8E1',
    },
    poetry: '蚯蚓结，麋角解，水泉动',
    poetryPicture: '/imgs/HeiSolarTerms/202422_poetry.png',
  },
  {
    name: '小寒',
    description: '寒意渐深',
    colors: {
      primary: '#3F51B5',
      accent: '#90A4AE',
      background: '#E8EAF6',
      ring: '#C5CAE9',
    },
    poetry: '雁北乡，鹊始巢，雉始鸲',
    poetryPicture: '/imgs/HeiSolarTerms/202423_poetry.png',
  },
  {
    name: '大寒',
    description: '严寒彻骨',
    colors: {
      primary: '#3949AB',
      accent: '#AB47BC',
      background: '#E8EAF6',
      ring: '#D1C4E9',
    },
    poetry: '鸡乳，征鸟厉疾，水泽腹坚',
    poetryPicture: '/imgs/HeiSolarTerms/202424_poetry.png',
  },
]
