export const themeList = [
  {
    name: '立春',
    color: '#94A07C',
    bgColor: '#FFFBF0',
    avatarImg: new URL('@/assets/Hei/solarTerms/罗小黑_2017_01_立春.avif', import.meta.url).href,
    cardImg: new URL('@/assets/Hei/solarTerms/罗小黑_2024_01_立春.jpg', import.meta.url).href,
  },
  {
    name: '雨水',
    color: '#8FA4A9',
    bgColor: '#FFFBF0',
    avatarImg: new URL('@/assets/Hei/solarTerms/罗小黑_2017_02_雨水.avif', import.meta.url).href,
    cardImg: new URL('@/assets/Hei/solarTerms/罗小黑_2024_02_雨水.jpg', import.meta.url).href,
  },
  {
    name: '惊蛰',
    color: '#4B7D7E',
    bgColor: '#FFFDF1',
    avatarImg: new URL('@/assets/Hei/solarTerms/罗小黑_2017_03_惊蛰.avif', import.meta.url).href,
    cardImg: new URL('@/assets/Hei/solarTerms/罗小黑_2024_03_惊蛰.jpg', import.meta.url).href,
  },
  {
    name: '春分',
    color: '#B4DB9C',
    bgColor: '#FFFDF1',
    avatarImg: new URL('@/assets/Hei/solarTerms/罗小黑_2017_04_春分.avif', import.meta.url).href,
    cardImg: new URL('@/assets/Hei/solarTerms/罗小黑_2024_04_春分.jpg', import.meta.url).href,
  },
  {
    name: '清明',
    color: '#B4CAB5',
    bgColor: '#FFFDF1',
    avatarImg: new URL('@/assets/Hei/solarTerms/罗小黑_2017_05_清明.avif', import.meta.url).href,
    cardImg: new URL('@/assets/Hei/solarTerms/罗小黑_2024_05_清明.jpg', import.meta.url).href,
  },
  {
    name: '谷雨',
    color: '#4A647B',
    bgColor: '#FFFDF1',
    avatarImg: new URL('@/assets/Hei/solarTerms/罗小黑_2017_06_谷雨.avif', import.meta.url).href,
    cardImg: new URL('@/assets/Hei/solarTerms/罗小黑_2024_06_谷雨.jpg', import.meta.url).href,
  },
  {
    name: '立夏',
    color: '#3C7031',
    bgColor: '#FFFBF0',
    avatarImg: new URL('@/assets/Hei/solarTerms/罗小黑_2017_07_立夏.avif', import.meta.url).href,
    cardImg: new URL('@/assets/Hei/solarTerms/罗小黑_2024_07_立夏.jpg', import.meta.url).href,
  },
  {
    name: '小满',
    color: '#FFCA7C',
    bgColor: '#FFFBF0',
    avatarImg: new URL('@/assets/Hei/solarTerms/罗小黑_2017_08_小满.avif', import.meta.url).href,
    cardImg: new URL('@/assets/Hei/solarTerms/罗小黑_2024_08_小满.jpg', import.meta.url).href,
  },
  {
    name: '芒种',
    color: '#9CAF9C',
    bgColor: '#FFFBF0',
    avatarImg: new URL('@/assets/Hei/solarTerms/罗小黑_2017_09_芒种.avif', import.meta.url).href,
    cardImg: new URL('@/assets/Hei/solarTerms/罗小黑_2024_09_芒种.jpg', import.meta.url).href,
  },
  {
    name: '夏至',
    color: '#83BEC4',
    bgColor: '#FFFBF0',
    avatarImg: new URL('@/assets/Hei/solarTerms/罗小黑_2017_10_夏至.avif', import.meta.url).href,
    cardImg: new URL('@/assets/Hei/solarTerms/罗小黑_2024_10_夏至.jpg', import.meta.url).href,
  },
  {
    name: '小暑',
    color: '#9CD7DD',
    bgColor: '#FFFBF0',
    avatarImg: new URL('@/assets/Hei/solarTerms/罗小黑_2017_11_小暑.avif', import.meta.url).href,
    cardImg: new URL('@/assets/Hei/solarTerms/罗小黑_2024_11_小暑.jpg', import.meta.url).href,
  },
  {
    name: '大暑',
    color: '#CE553A',
    bgColor: '#FFFBF0',
    avatarImg: new URL('@/assets/Hei/solarTerms/罗小黑_2017_12_大暑.avif', import.meta.url).href,
    cardImg: new URL('@/assets/Hei/solarTerms/罗小黑_2024_12_大暑.jpg', import.meta.url).href,
  },
  {
    name: '立秋',
    color: '#D54D0F',
    bgColor: '#FFFBF0',
    avatarImg: new URL('@/assets/Hei/solarTerms/罗小黑_2017_13_立秋.avif', import.meta.url).href,
    cardImg: new URL('@/assets/Hei/solarTerms/罗小黑_2024_13_立秋.jpg', import.meta.url).href,
  },
]
