export const themeList = [
  {
    name: '立春',
    color: '#94B79E',
    bgColor: '#E7F3CF',
    avatarImg: new URL('@/assets/Hei/solarTerms/罗小黑_2017_01_立春.avif', import.meta.url).href,
    cardImg: new URL('@/assets/Hei/solarTerms/罗小黑_2024_01_立春.jpg', import.meta.url).href,
  },
  {
    name: '雨水',
    color: '#F8B1A3',
    bgColor: '#BDD2D7',
    avatarImg: new URL('@/assets/Hei/solarTerms/罗小黑_2017_02_雨水.avif', import.meta.url).href,
    cardImg: new URL('@/assets/Hei/solarTerms/罗小黑_2024_02_雨水.jpg', import.meta.url).href,
  },
  {
    name: '惊蛰',
    color: '#DC9EB5',
    bgColor: '#7CAEAD',
    avatarImg: new URL('@/assets/Hei/solarTerms/罗小黑_2017_03_惊蛰.avif', import.meta.url).href,
    cardImg: new URL('@/assets/Hei/solarTerms/罗小黑_2024_03_惊蛰.jpg', import.meta.url).href,
  },
  {
    name: '春分',
    color: '#88A6CA',
    bgColor: '#B4DB9C',
    avatarImg: new URL('@/assets/Hei/solarTerms/罗小黑_2017_04_春分.avif', import.meta.url).href,
    cardImg: new URL('@/assets/Hei/solarTerms/罗小黑_2024_04_春分.jpg', import.meta.url).href,
  },
  {
    name: '清明',
    color: '#A398B7',
    bgColor: '#B4CAB5',
    avatarImg: new URL('@/assets/Hei/solarTerms/罗小黑_2017_05_清明.avif', import.meta.url).href,
    cardImg: new URL('@/assets/Hei/solarTerms/罗小黑_2024_05_清明.jpg', import.meta.url).href,
  },
  {
    name: '谷雨',
    color: '#E29DAE',
    bgColor: '#214118',
    avatarImg: new URL('@/assets/Hei/solarTerms/罗小黑_2017_06_谷雨.avif', import.meta.url).href,
    cardImg: new URL('@/assets/Hei/solarTerms/罗小黑_2024_06_谷雨.jpg', import.meta.url).href,
  },
  {
    name: '立夏',
    color: '#9AB085',
    bgColor: '#FFCA7C',
    avatarImg: new URL('@/assets/Hei/solarTerms/罗小黑_2017_07_立夏.avif', import.meta.url).href,
    cardImg: new URL('@/assets/Hei/solarTerms/罗小黑_2024_07_立夏.jpg', import.meta.url).href,
  },
  {
    name: '小满',
    color: '#BE6F77',
    bgColor: '#FCD291',
    avatarImg: new URL('@/assets/Hei/solarTerms/罗小黑_2017_08_小满.avif', import.meta.url).href,
    cardImg: new URL('@/assets/Hei/solarTerms/罗小黑_2024_08_小满.jpg', import.meta.url).href,
  },
  {
    name: '芒种',
    color: '#D27B6D',
    bgColor: '#9CAF9C',
    avatarImg: new URL('@/assets/Hei/solarTerms/罗小黑_2017_09_芒种.avif', import.meta.url).href,
    cardImg: new URL('@/assets/Hei/solarTerms/罗小黑_2024_09_芒种.jpg', import.meta.url).href,
  },
  {
    name: '夏至',
    color: '#87A9BB',
    bgColor: '#83BEC4',
    avatarImg: new URL('@/assets/Hei/solarTerms/罗小黑_2017_10_夏至.avif', import.meta.url).href,
    cardImg: new URL('@/assets/Hei/solarTerms/罗小黑_2024_10_夏至.jpg', import.meta.url).href,
  },
  {
    name: '小暑',
    color: '#82A79B',
    bgColor: '#9CD7DD',
    avatarImg: new URL('@/assets/Hei/solarTerms/罗小黑_2017_11_小暑.avif', import.meta.url).href,
    cardImg: new URL('@/assets/Hei/solarTerms/罗小黑_2024_11_小暑.jpg', import.meta.url).href,
  },
  {
    name: '大暑',
    color: '#E29495',
    bgColor: '#CE553A',
    avatarImg: new URL('@/assets/Hei/solarTerms/罗小黑_2017_12_大暑.avif', import.meta.url).href,
    cardImg: new URL('@/assets/Hei/solarTerms/罗小黑_2024_12_大暑.jpg', import.meta.url).href,
  },
  {
    name: '立秋',
    color: '#BF8DA9',
    bgColor: '#D54D0F',
    avatarImg: new URL('@/assets/Hei/solarTerms/罗小黑_2017_13_立秋.avif', import.meta.url).href,
    cardImg: new URL('@/assets/Hei/solarTerms/罗小黑_2024_13_立秋.jpg', import.meta.url).href,
  },
  {
    name: '处暑',
    color: '#BB8CB7',
    bgColor: '#08243A',
    avatarImg: new URL('@/assets/Hei/solarTerms/罗小黑_2017_14_处暑.avif', import.meta.url).href,
    cardImg: new URL('@/assets/Hei/solarTerms/罗小黑_2024_14_处暑.jpg', import.meta.url).href,
  },
  {
    name: '白露',
    color: '#7789AB',
    bgColor: '#001F31',
    avatarImg: new URL('@/assets/Hei/solarTerms/罗小黑_2017_15_白露.avif', import.meta.url).href,
    cardImg: new URL('@/assets/Hei/solarTerms/罗小黑_2024_15_白露.jpg', import.meta.url).href,
  },
  {
    name: '秋分',
    color: '#E4AB63',
    bgColor: '#D69129',
    avatarImg: new URL('@/assets/Hei/solarTerms/罗小黑_2017_16_秋分.avif', import.meta.url).href,
    cardImg: new URL('@/assets/Hei/solarTerms/罗小黑_2024_16_秋分.jpg', import.meta.url).href,
  },
  {
    name: '寒露',
    color: '#C5B385',
    bgColor: '#BDC9D5',
    avatarImg: new URL('@/assets/Hei/solarTerms/罗小黑_2017_17_寒露.avif', import.meta.url).href,
    cardImg: new URL('@/assets/Hei/solarTerms/罗小黑_2024_17_寒露.jpg', import.meta.url).href,
  },
  {
    name: '霜降',
    color: '#D299A0',
    bgColor: '#CEBEAE',
    avatarImg: new URL('@/assets/Hei/solarTerms/罗小黑_2017_18_霜降.avif', import.meta.url).href,
    cardImg: new URL('@/assets/Hei/solarTerms/罗小黑_2024_18_霜降.jpg', import.meta.url).href,
  },
  {
    name: '立冬',
    color: '#D47568',
    bgColor: '#8CB9D6',
    avatarImg: new URL('@/assets/Hei/solarTerms/罗小黑_2017_19_立冬.avif', import.meta.url).href,
    cardImg: new URL('@/assets/Hei/solarTerms/罗小黑_2024_19_立冬.jpg', import.meta.url).href,
  },
]
